baseURL = 'https://tomodachii.com/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"

[markup.goldmark.renderer]
  unsafe = true

[params.authorLinks]
Tomodachii = "https://github.com/tomodachii"
"John N. Tsitsiklis" = "https://web.mit.edu/jnt/www/home.html"
"Michael R. Garey" = "https://en.wikipedia.org/wiki/Michael_Garey"
"David S. Johnson" = "https://en.wikipedia.org/wiki/David_S._Johnson"
"Chris Piech" = "https://stanford.edu/~cpiech/bio/index.html"
"B.W. Silverman" = "https://en.wikipedia.org/wiki/Bernard_Silverman"
"Daphne Koller" = "https://ai.stanford.edu/~koller/index.html"
"Nir Friedman" = "https://www.cs.huji.ac.il/w~nir/"
"Carl Edward Rasmussen" = "https://mlg.eng.cam.ac.uk/carl/"
"Christopher K. I. Williams" = "https://homepages.inf.ed.ac.uk/ckiw/"
"Kevin P. Murphy" = "https://www.cs.ubc.ca/~murphyk/"