baseURL = 'https://tomodachii.github.io/tomodachii-blog/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"